# SPDX-FileCopyrightText: © 2020 Alias Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
#
# SPDX-License-Identifier: MIT

FROM spectreproject/spectre-builder-debian-stretch:1.6
MAINTAINER HLXEasy <hlxeasy@gmail.com>

RUN rm -rf /var/lib/apt/lists/* \
 && apt-get update -y \
 && apt-get install -y gcc-9-base libgcc-9-dev libc6-dev \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
    cmake \
    libqt5network5 \
    libqt5quick5 \
    libqt5quickwidgets5 \
    libqt5svg5-dev \
    libqt5webchannel5-dev \
    libqt5websockets5-dev \
    libqt5webview5-dev \
    libqt5widgets5 \
 && apt-get clean
